# This is a template for building a function app and deploy it to azure

parameters:
    appProjectsPath: '**/*.csproj'
    testProjectsPath: ''
    jobName: 'FunctionApp'
    azureSubscription: ''
    webAppName: ''
    appSettings: ''

jobs:
- job: 'PR_${{parameters.jobName}}'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  pool:
    vm-image: 'windows-latest'
  steps:
  - template: ../steps/run-tests.yml
    parameters:
      testProjectsPath: ${{parameters.testProjectsPath}}
- job: 'CI_${{parameters.jobName}}'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  pool:
    vm-image: 'windows-latest'
  steps:
  - template: ../steps/run-tests.yml
    parameters:
      testProjectsPath: ${{parameters.testProjectsPath}}
  - template: ../steps/publish-functionapp.yml
    #condition: and(succeeded(), ne(Build.Reason, 'PullRequest'))
    parameters:
      appProjectsPath: ${{parameters.appProjectsPath}}
      buildConfiguration: 'Debug'
  - template: ../steps/deploy-functionapp.yml
    #condition: and(succeeded(), ne(Build.Reason, 'PullRequest'))
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      webAppName: ${{parameters.webAppName}}
      appSettings: ${{parameters.appSettings}}
 
