# This is a template for creating a nuget based on .NET Core
# Based on information at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts

parameters:
  nugetProjectsPath: ''
  testProjectsPath: ''
  jobName: 'NuGet'
  nuGetFeedType: 'internal' # internal or external
  publishVstsFeed: '' # Required for internal. A guid
  publishFeedCredentials: '' # Required for external. A service connection.

jobs:
- job: 'PR_${{parameters.jobName}}'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ../steps/run-tests.yml
    parameters:
      testProjectsPath: ${{parameters.testProjectsPath}}
- job: 'CI_${{parameters.jobName}}'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ../steps/run-tests.yml
    parameters:
      testProjectsPath: ${{parameters.testProjectsPath}}
  - template: ../steps/pack-nuget.yml
    parameters:
      nugetProjectsPath: ${{parameters.nugetProjectsPath}}
  - template: ../steps/push-nuget.yml
    parameters:
      nuGetFeedType: ${{parameters.nuGetFeedType}}
      publishFeedCredentials: ${{parameters.publishFeedCredentials}}
      publishVstsFeed: ${{parameters.publishVstsFeed}}