# This is a template for building a web app and make an artifact available

parameters:
    appProjectsPath: '**/*.csproj'
    testProjectsPath: ''
    jobName: 'WebApp Artifact'

jobs:
- job: 'PR_${{parameters.jobName}}'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ../steps/run-tests.yml
    parameters:
      testProjectsPath: ${{parameters.testProjectsPath}}
- job: 'CI_${{parameters.jobName}}'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ../steps/run-tests.yml
    parameters:
      testProjectsPath: ${{parameters.testProjectsPath}}
  - template: ../steps/run-tests.yml
    parameters:
      testProjectsPath: ${{parameters.testProjectsPath}}
  - template: ../steps/publish-webapp-artifact.yml
    parameters:
      appProjectsPath: ${{parameters.appProjectsPath}}
      buildConfiguration: 'Debug'

